from __future__ import annotations

from io import BytesIO

import pandas as pd

SHEET_ORDER = [
    "Raw_Data",
    "Turn_Level_Analysis",
    "Code_Request_Events",
    "Session_Summary",
    "Question_Summary",
    "Validation_Report",
    "Data_Dictionary",
]


def _safe_sheet_df(df):
    out = pd.DataFrame() if df is None else df.copy()
    for col in out.columns:
        series = out[col]
        if pd.api.types.is_datetime64_any_dtype(series):
            try:
                out[col] = series.dt.tz_localize(None)
            except (TypeError, AttributeError):
                pass
        elif series.dtype == "object":
            def make_excel_safe(value):
                if value is None:
                    return value
                if isinstance(value, pd.Timestamp):
                    return value.tz_localize(None) if value.tzinfo is not None else value
                if hasattr(value, "tzinfo") and hasattr(value, "replace"):
                    try:
                        if value.tzinfo is not None:
                            return value.replace(tzinfo=None)
                    except Exception:
                        pass
                return value
            out[col] = series.map(make_excel_safe)
    return out


def _data_dictionary(tables):
    rows = []
    for sheet_name, df in tables.items():
        if df is None:
            continue
        for col in df.columns:
            rows.append({
                "sheet": sheet_name,
                "field": col,
                "dtype": str(df[col].dtype),
                "description": "Generated by the conversational-assessment processing pipeline.",
            })
    return pd.DataFrame(rows)


def build_standardized_workbook(raw, turns, sessions, questions, requests, validation):
    tables = {
        "Raw_Data": raw,
        "Turn_Level_Analysis": turns,
        "Code_Request_Events": requests,
        "Session_Summary": sessions,
        "Question_Summary": questions,
        "Validation_Report": validation,
    }
    tables["Data_Dictionary"] = _data_dictionary(tables)

    bio = BytesIO()
    with pd.ExcelWriter(bio, engine="openpyxl") as writer:
        for sheet in SHEET_ORDER:
            _safe_sheet_df(tables.get(sheet, pd.DataFrame())).to_excel(
                writer, sheet_name=sheet, index=False
            )
    bio.seek(0)
    return bio
